# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#PyQt5 imports  
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QInputDialog, QLineEdit, QMessageBox

#module imports
from DA_CallMain import RunSystem, StopSystem    
# import the packages for connection
from DA_Connection import create_mysql_connection, create_plc_connection

# import standard lib from python
import sys
import os
import csv
import datetime
import threading
import atexit

# import packeges for sending mail
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders

#################        #STARTING THE CLASS FOR GUI  ###################################
class Ui_MainWindow(object):
        #START SET UP GUI
        def setupUi(self, MainWindow):
                self.MySQLconn = None
                self.PLCconn = None
                
                atexit.register(self.cleanup_on_exit)
                MainWindow.closeEvent = self.closeEvent
                
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1000, 520)
                MainWindow.setStyleSheet("\n""background-color: rgb(250, 250, 250);")
                
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                #end setting the central widget - main window
                
                #setting secondary widget 
                self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
                self.tabWidget.setGeometry(QtCore.QRect(0, 0, 900, 520))
                self.tabWidget.setStyleSheet("""
                        QTabBar::tab {
                                min-width: 150px;
                                background-color: rgb(0,255,255);
                                color: rgb(0, 0, 100);
                                border: 2px solid rgb(0, 0, 100);
                                border-top-left-radius: 8px;
                                border-top-right-radius: 8px;
                                padding: 6px;
                                margin: 2px;
                                font-size: 18px;
                        }
                        QTabBar::tab:selected {
                                background-color: rgb(0, 0, 100);
                                color: white;
                        }

                        QTabBar::tab:!selected{
                                background-color: rgb(255, 255, 255);
                                color: rgb(0, 0, 100);
                                border: 1px solid rgb(0, 0, 100);
                        }
                """)
                self.tabWidget.setObjectName("tabWidget")
                
                #tab1 - main window
                self.tab1 = QtWidgets.QWidget()
                self.tab1.setObjectName("tab1")
                #setting title of the window
                
                self.title = QtWidgets.QLabel(self.tab1)
                self.title.setGeometry(QtCore.QRect(130,5 , 700, 52))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.title.setFont(font)
                self.title.setAlignment(QtCore.Qt.AlignCenter)
                self.title.setStyleSheet("""
                        QLabel
                        {
                                background-color: rgb(0, 0, 100);
                                color: rgb(253, 253, 253);
                                padding: 5px;
                                font-size: 20px;
                                border-radius: 10px;
                                border: none;
                                padding: 10px;
                        }
                                        """)
                self.title.setObjectName("title")
                #setting title of the window - end

                #setting start system button
                self.pushButton = QtWidgets.QPushButton(self.tab1)
                self.pushButton.setGeometry(QtCore.QRect(130, 420, 150, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton.setFont(font)
                self.pushButton.setStyleSheet("""
                        QPushButton 
                        {
                                background-color: rgb(0, 0, 100);
                                color: rgb(250, 250, 250);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: none;
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(255, 255, 255);
                                color: rgb(0, 0, 100);
                                border: 3px solid rgb(0, 0, 100);
                        }
                """)
                self.pushButton.setObjectName("pushButton")
                #setting start system button - end
                
                #setting stop system button
                self.pushButton_2 = QtWidgets.QPushButton(self.tab1)
                self.pushButton_2.setGeometry(QtCore.QRect(330, 420, 150, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("""
                        QPushButton
                        {
                                background-color: rgb(255, 0, 0);
                                color: rgb(250, 250, 250);
                                padding: 5px;
                                font-size: 15px;
                                border-radius:10px;
                                border: none;
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(255, 255, 255);
                                color: rgb(255, 0, 0);
                                border: 3px solid rgb(255, 0, 0);
                        }
                """)
                self.pushButton_2.setObjectName("pushButton_2")
                #setting stop system button - end
                
                #setting connect device button
                self.pushButton_3 = QtWidgets.QPushButton(self.tab1)
                self.pushButton_3.setGeometry(QtCore.QRect(10, 60, 110, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setStyleSheet("""
                        QPushButton 
                        {
                                background-color: rgb(0, 100, 0);
                                color: rgb(240, 240, 240);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: none;
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(255, 255,255 );
                                color: rgb(0, 100, 0);
                                border: 3px solid rgb(0, 100, 0);
                        }
                """)
                self.pushButton_3.setObjectName("pushButton_3")
                #setting Connect device button - end
                
                #setting disconnect device button
                self.pushButton_4 = QtWidgets.QPushButton(self.tab1)
                self.pushButton_4.setGeometry(QtCore.QRect(10,130, 110, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_4.setFont(font)
                self.pushButton_4.setStyleSheet("""
                        QPushButton 
                        {
                                background-color: rgb(255,200 , 0);
                                color: rgb(0, 0, 100);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: none;
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(255, 255,255 );
                                color: rgb(0, 0, 100);
                                border: 2px solid rgb(255, 140, 0);
                        }
                """)
                self.pushButton_4.setObjectName("pushButton_4")
                #setting Connect device button - end
                
                #setting reset button
                self.pushButton_8 = QtWidgets.QPushButton(self.tab1)
                self.pushButton_8.setGeometry(QtCore.QRect(10,420, 110, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_8.setFont(font)
                self.pushButton_8.setStyleSheet("""
                     QPushButton 
                        {
                                background-color: rgb(255, 255, 255);
                                color: rgb(0, 0, 100);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: 2px solid rgb(0, 0, 100);
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(0, 0, 100);
                                color: rgb(255, 255, 255);
                                border: none;
                        }
                """)
                self.pushButton_8.setObjectName("pushButton_8")
                #end setting reset button
                
                #setting display frame for camera
                self.label = QtWidgets.QLabel(self.tab1)
                self.label.setGeometry(QtCore.QRect(130, 60, 350, 350))
                self.label.setObjectName("label")
                self.label.setStyleSheet("border: 2px dashed rgb(10,10,10); background-color: rgb(240,240,240);")
                #setting display frame for camera - end
                
                #setting display frame for image in processing
                self.label_2 = QtWidgets.QLabel(self.tab1)
                self.label_2.setGeometry(QtCore.QRect(530, 60, 300, 300))
                self.label_2.setObjectName("label_2")
                self.label_2.setStyleSheet("border: 2px dashed rgb(10,10,10); background-color: rgb(240,240,240);")
                #setting display frame for image in processing - end
                self.btn_reset = QtWidgets.QPushButton("Reset")
                self.btn_reset.setFixedWidth(90)
                
                #start setting show num of products in processing
                self.groupBox_stats = QtWidgets.QGroupBox(self.tab1)
                self.groupBox_stats.setGeometry(QtCore.QRect(10, 225, 110, 180))
                self.groupBox_stats.setStyleSheet("""
                        QGroupBox {
                                font-weight: bold;
                                background-color: rgb(0, 0, 100);
                                border: 2px solid rgb(0, 0, 100);
                                border-radius: 6px;
                                padding: 3px;
                        }
                        """)
                stats_layout = QtWidgets.QVBoxLayout(self.groupBox_stats)
                # label number for each product
                self.label_sb = QtWidgets.QLabel("SB: 0")
                self.label_st = QtWidgets.QLabel("ST: 0")
                self.label_sf = QtWidgets.QLabel("SF: 0")
                self.label_er = QtWidgets.QLabel("ER: 0")
                self.label_total = QtWidgets.QLabel("Total: 0")

                for lbl in [self.label_sb, self.label_st, self.label_sf, self.label_er, self.label_total]:
                        lbl.setStyleSheet("font-size: 18px; "
                                        "background-color: rgb(0, 0, 100);"
                                        "color: rgb(255, 255, 255); ")
                        stats_layout.addWidget(lbl)
                
                #end setting the label for product count

                self.tabWidget.addTab(self.tab1, "Control")
                #tab1 - main window - end
                
                #sẻtting tab2 - database handling
                self.tab2 = QtWidgets.QWidget()
                self.tab2.setObjectName("tab2")
                # Show Data from MySQL
                self.tableWidget = QtWidgets.QTableWidget(self.tab2)
                self.tableWidget.setGeometry(QtCore.QRect(50, 55, 820, 400))
                self.tableWidget.setColumnCount(6)
                
                self.tableWidget.setHorizontalHeaderLabels(["ID", "type", "Name", "NSX", "Time","Status",])
                self.tableWidget.horizontalHeader().setStretchLastSection(True)
                self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
                self.tableWidget.setShowGrid(True)

                # setting the size of the columns by data length
                self.tableWidget.setColumnWidth(0, 80)   # ID
                self.tableWidget.setColumnWidth(1, 60)   # type
                self.tableWidget.setColumnWidth(2, 150)  # name
                self.tableWidget.setColumnWidth(3, 150)  # NSX
                self.tableWidget.setColumnWidth(4, 140)  # time
                self.tableWidget.setColumnWidth(5, 130)  # status

                #setting the tableWidget - end
                
                self.tableWidget.setStyleSheet("""
                        QHeaderView::section {
                                background-color: rgb(0, 0, 100); 
                                color: rgb(255, 255, 255);                 
                                font-weight: bold;
                                padding: 3px;
                                border: 1px solid rgb(0, 0, 100);
                        }
                        QTableWidget {
                                gridline-color: rgb(0, 0, 0);
                                background-color: white;
                                alternate-background-color: rgb(245, 245, 255);
                        }
                """)
                #setting Show Data button
                self.pushButton_5 = QtWidgets.QPushButton(self.tab2)
                self.pushButton_5.setGeometry(QtCore.QRect(50, 2, 150, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_5.setFont(font)
                self.pushButton_5.setStyleSheet("""
                        QPushButton 
                        {
                                background-color: rgb(255, 255, 255);
                                color: rgb(0, 0, 100);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: 2px solid rgb(0, 0, 100);
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(0, 0, 100);
                                color: rgb(255, 255, 255);
                                border: none;
                        }
                """)
                self.pushButton_5.setObjectName("pushButton_5")
                #setting start system button - end

                #setting export device button
                self.pushButton_6 = QtWidgets.QPushButton(self.tab2)
                self.pushButton_6.setGeometry(QtCore.QRect(510,2, 150, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_6.setFont(font)
                self.pushButton_6.setStyleSheet("""
                        QPushButton 
                        {
                                background-color: rgb(255, 200, 0);
                                color: rgb(0, 0, 100);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: none;
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(255, 255,255 );
                                color: rgb(0, 0, 100);
                                border: 2px solid rgb(255, 200, 0);
                        }
                """)
                self.pushButton_6.setObjectName("pushButton_6")
                
                #setting send mail button
                self.pushButton_7 = QtWidgets.QPushButton(self.tab2)
                self.pushButton_7.setGeometry(QtCore.QRect(675, 2, 150, 50))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_7.setFont(font)
                self.pushButton_7.setStyleSheet("""
                        QPushButton 
                        {
                                background-color: rgb(0, 100, 0);
                                color: rgb(240, 240, 240);
                                padding: 5px;
                                font-size: 15px;
                                border-radius: 10px;
                                border: none;
                        }
                        QPushButton:hover
                        {
                                background-color: rgb(255, 255,255 );
                                color: rgb(0, 100, 0);
                                border: 3px solid rgb(0, 100, 0);
                        }
                """)
                self.pushButton_7.setObjectName("pushButton_7")
                #end tab 2 - database handling
                self.tabWidget.addTab(self.tab2, "Statistics")
             
                MainWindow.setCentralWidget(self.centralwidget)
                self.retranslateUi(MainWindow)
################################    END SET UP GUI                ############################################

################################    START SETTING BUTTON FUNCTIONS ############################################               
                #start camera button
                self.pushButton.clicked.connect(self.start_camera)
                
                #stop camera button
                self.pushButton_2.clicked.connect(self.stop_camera)

                #connect to MySQL and PLC button
                self.pushButton_3.clicked.connect(self.connect)

                #disconnect to MySQL and PLC button
                self.pushButton_4.clicked.connect(self.disconnect)
                
                #Launch the function to load data from MySQL to tableWidget 
                self.pushButton_5.clicked.connect(self.load_from_mysql)     

                #export data button
                self.pushButton_6.clicked.connect(self.export_data)   

                #sending mail button
                self.pushButton_7.clicked.connect(self.SendMail)

                #reset button
                self.pushButton_8.clicked.connect(self.resetDB)
#################################    END SETTING BUTTON FUNCTIONS ############################################        

#################    STARTING THE TIMER TO UPDATE THE NUMBER OF PRODUCTS IN PROCESSING ########################
                self.timer = QtCore.QTimer()
                self.timer.timeout.connect(self.update_product_count) #call the function to update the number of products in processing
                self.timer.start(200) #update every 1 second

#################   END STARTING THE TIMER TO UPDATE THE NUMBER OF PRODUCTS IN PROCESSING ###########################
        #RENAME THE TEXT IN THE GUI
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                #title of the window             
                MainWindow.setWindowTitle(_translate("MainWindow", "QR Sorting System"))
                self.title.setText(_translate("MainWindow", "Control Pannel For QR sorting system"))
                
                #buttons text
                #setting the text for buttons in tab1
                self.pushButton.setText(_translate("MainWindow", "Start Camera"))
                self.pushButton_2.setText(_translate("MainWindow", "Stop Camera"))
                self.pushButton_3.setText(_translate("MainWindow", "Connect"))
                self.pushButton_4.setText(_translate("MainWindow", "Disconnect"))
                self.pushButton_8.setText(_translate("MainWindow", "Reset"))

                #setting the text for buttons in tab2
                self.pushButton_5.setText(_translate("MainWindow", "Show Data"))
                self.pushButton_6.setText(_translate("MainWindow", "Export Data"))
                self.pushButton_7.setText(_translate("MainWindow", "Send Mail"))

                #camera display text
                self.label.setText(_translate("MainWindow", "Camera Display"))
                self.label_2.setText(_translate("MainWindow", "Image in Processing"))
                #self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        
        # START SETTING BUTTON FUNCTIONS
        # CREATE CONNECTION TO MYSQL AND PLC

        def connect(self) -> None:
                if self.MySQLconn != None and self.PLCconn != None:
                        msg = "MySQL has been connected\nPLC has been connected"
                        QtWidgets.QMessageBox.information(None, "Connection Status", msg)
                        return
                
                success_msgs = []
                error_msgs = []
                # MySQL
                try:
                        self.MySQLconn = create_mysql_connection()
                        if self.MySQLconn.getStatusConnection():
                                success_msgs.append("MySQL: Connected successfully")
                        else:
                                error_msgs.append("MySQL: Connection failed")
                except Exception as e:
                        error_msgs.append(f"MySQL: Error - {e}")

                # PLC
                try:
                        self.PLCconn = create_plc_connection()
                        if self.PLCconn.isConnected:
                                success_msgs.append("PLC: Connected successfully")
                        else:
                                error_msgs.append("PLC: Connection failed")
                except Exception as e:
                        error_msgs.append(f"PLC: Error - {e}")

                #show the status of connection
                message = "\n".join(success_msgs + error_msgs)
                if self.PLCconn == None or self.MySQLconn == None:
                        QtWidgets.QMessageBox.warning(None, "Connection Status", message)
                else:
                        QtWidgets.QMessageBox.information(None, "Connection Status", message)

        # DISCONNECT MYSQL AND PLC
        def disconnect(self):
                #close MySQL and PLC connection
                if self.MySQLconn is None and self.PLCconn is None:
                        QtWidgets.QMessageBox.warning(None, "Warning", "Please connect to MySQL and PLC first.")
                        return
                close_status = []
                try:
                        self.MySQLconn.closeConnection()
                        close_status.append("MySQL connection closed.")
                except Exception as e:
                        close_status.append(f"Error closing MySQL connection, Maybe it not open :D")
                #close MySQL connection
                try:
                        self.PLCconn.closeConnection()
                        close_status.append("PLC connection closed.")
                except Exception as e:
                        close_status.append(f"Error closing PLC connection, May be it not open :D")
                self.MySQLconn = None
                self.PLCconn = None
                #show the status of closing connection
                QtWidgets.QMessageBox.information(None, "Disconnect", "\n".join(close_status))

        #OPEN CAMERA AND START THE SYSTEM
        def start_camera(self):
                #create a thread to run the system
                if self.MySQLconn is None:
                        QtWidgets.QMessageBox.warning(None, "Warning", "Please connect to MySQL and PLC first.")
                        return
                threading.Thread(target=RunSystem, args=(self.label, self.label_2,self.MySQLconn,self.PLCconn)).start()
        
        #STOP CAMERA THE CAMERA
        def stop_camera(self):
                #stop the thread is running camera
                StopSystem()
                
                #clear camera on screen
                self.label.clear()
                self.label.setText("Camera display")
                
                self.label_2.clear()
                self.label_2.setText("Camera display")
        
        #SHOW DATA FROM MYSQL TO TABLEWIDGET
        def load_from_mysql(self):
                if self.MySQLconn is None:
                        QtWidgets.QMessageBox.warning(None, "Warning", "Please connect to MySQL server first.")
                        return
                try:
                        results = self.MySQLconn.showTableQRisSorted() #save the result of query to results as a list of tuples
                        self.tableWidget.setRowCount(len(results)) # Set the number of rows in the table is the number of results
                        for row_idx, row_data in enumerate(results): # enumerate the results to get the index and data of each row
                                for col_idx, value in enumerate(row_data):
                                        item = QtWidgets.QTableWidgetItem(str(value)) # Convert the value to string
                                        item.setTextAlignment(QtCore.Qt.AlignCenter)
                                        self.tableWidget.setItem(row_idx, col_idx, item)
                except Exception as e:
                        QtWidgets.QMessageBox.critical(None, "MySQL Error", f"\n{e}")
        
        #EXPORT DATA TO CSV FILE
        def export_data(self):
                # create folder if not exist
                if not os.path.exists("ExportFile"):
                        os.makedirs("ExportFile")

                #check if the MySQL connection is None
                if self.MySQLconn is None:
                        QtWidgets.QMessageBox.warning(None, "Warning", "Please connect to MySQL server first.")
                        return
                
                #set the path to save the file
                filepath = f"ExportFile/list_sorted_export_on_{datetime.datetime.now().strftime('%Y-%m-%d_%Hh%Mm%Ss')}.csv" 
                try:
                        with open(filepath, mode='w', newline='') as file: #using with to open the file, it will close the file after using
                                writer = csv.writer(file)  #write the header of the table
                                #write the data of the table
                                for row in range(self.tableWidget.rowCount()):
                                        row_data = []
                                        for col in range(self.tableWidget.columnCount()):
                                                item = self.tableWidget.item(row, col)
                                                if item is not None:
                                                        row_data.append(item.text())
                                                else:
                                                        row_data.append('')
                                        writer.writerow(row_data)
                        QtWidgets.QMessageBox.information(None, "Export Data", f"Data exported successfully.")
                except Exception as e:
                        QtWidgets.QMessageBox.critical(None, "Export Error", f"Error exporting due to: {e}")
                #show the status of export data
        
        #send the file to email
        def SendMail(self,filepath:str) -> None:

                #choose the file to send                
                filepath, _ = QFileDialog.getOpenFileName(None, "Select CSV File", "ExportFile", "CSV Files (*.csv)")
                
                # create the email ender
                sender_email = 'qrsortingsystem@gmail.com'
                sender_password = 'gcgu zvyy pbxb nsua' # pass in App Password of the sender email: gcgu zvyy pbxb nsua

                #email sender will be input by user                
                reciever_email, ok = QInputDialog.getText(None, "Input email", "Enter the email address to send: ", QLineEdit.Normal)
                
                #not ok mean user cancel the input dialog, not reciever_email mean user not enter the email address
                if not ok or not reciever_email:
                        return        
                
                #write the code to send the email
                try:
                        msg = MIMEMultipart() #create the object email, it can be used to send the email with attachment
                        msg['From'] = sender_email # name mail sender
                        msg['To'] = reciever_email # reciever email address, be intput by user
                        msg['Subject'] = "list QR product Sorting Data" #subject of the email
                        msg.attach(MIMEText("This is the file report sent from QR sorting System,\n Do not reply this mail", 'plain')) #plain mean the text is not html
                        
                        # attach CSV file to email
                        with open(filepath, 'rb') as f:
                                #default for attach mail
                                part = MIMEBase('application', 'octet-stream') #default type MIME for binary file
                                part.set_payload(f.read()) #read the file in binary mode
                                encoders.encode_base64(part) #encode the file to base64, it compulsory to send the file as attachment
                               
                                # remove path file to tak file name only
                                part.add_header('Content-Disposition', # name of HTTP header email 
                                                f"attachment; filename='{filepath.split('/')[-1]}'")
                                
                                # attach the file to the email
                                msg.attach(part)
                        # send the email by using SMTP_SSL: Simple Mail Transfer Protocol
                        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server: 
                                #'smtp.gmail.com' is the Google SMTP server of Gmail, 
                                # 465 is the port number
                                # 587 is the port number for TLS, but we use SSL here
                                server.login(sender_email, sender_password) #login to the sender email account
                                server.send_message(msg)
                        
                        QtWidgets.QMessageBox.information(None, "Send Mail Success", "Mail sent successfully\nCheck your email.")
                except Exception as e:
                        QtWidgets.QMessageBox.critical(None, "Send Mail Error", f"Error sending mail due to: {e}")
                        return
        #END SETTING BUTTON FUNCTIONS

        #START UPDATING THE FUNCTION FOR THE NUMBER OF PRODUCTS IN PROCESSING
        def update_product_count(self) -> None:
                #check if the MySQL connection is None
                if self.MySQLconn is None:
                        return
                
                cursor = self.MySQLconn.conn.cursor(buffered=True)
                cursor.execute("""
                        SELECT numSB, numST, numSF, numER, total_number_of_products
                        FROM number_of_products
                """)
                row = cursor.fetchone()
                cursor.close()
                if row:
                        #update the number of products in processing
                        self.label_sb.setText(f"SB: {row[0]}")
                        self.label_st.setText(f"ST: {row[1]}")
                        self.label_sf.setText(f"SF: {row[2]}")
                        self.label_er.setText(f"ER: {row[3]}")
                        self.label_total.setText(f"Total: {row[4]}")
                        #update the label for each product count
                else:
                        self.label_sb.setText("SB: 0")
                        self.label_st.setText("ST: 0")
                        self.label_sf.setText("SF: 0")
                        self.label_er.setText("ER: 0")
                        self.label_total.setText("Total: 0")
        # END UPDATING THE FUNCTION FOR THE NUMBER OF PRODUCTS IN PROCESSING
        
        #START RESET DATABASE
        def resetDB(self) -> None:
                #reset the database
                if self.MySQLconn is None:
                        QtWidgets.QMessageBox.warning(None, "Warning", "Please connect to MySQL server first.")
                        return
                self.MySQLconn.resetDB()
                QtWidgets.QMessageBox.information(None, "Database Reset", "Database reset successfully.")
        #END RESET DATABASE
        
        ######################### EXIT GUI #########################
        def closeEvent(self, event):
                """Handle window close event"""
                try:
                        # Stop the camera system first
                        StopSystem()
                        
                        # Stop the timer
                        if hasattr(self, 'timer'):
                                self.timer.stop()
                        
                        # Disconnect from devices
                        self.cleanup_connections()
                        
                        # Show goodbye message
                        QtWidgets.QMessageBox.information(None, "System Shutdown", 
                                                        "System stopped safely.\nAll connections closed.")
                        
                        # Accept the close event
                        event.accept()
                        
                except Exception as e:
                        print(f"Error during shutdown: {e}")
                        event.accept()  # Still close even if there's an error

        def cleanup_connections(self):
                """Clean up MySQL and PLC connections"""
                close_status = []
                
                # Close MySQL connection
                if self.MySQLconn is not None:
                        try:
                                self.MySQLconn.closeConnection()
                                close_status.append("MySQL connection closed successfully")
                                print("MySQL connection closed")
                        except Exception as e:
                                close_status.append(f"Error closing MySQL: {e}")
                                print(f"Error closing MySQL: {e}")
                        finally:
                                self.MySQLconn = None

                # Close PLC connection  
                if self.PLCconn is not None:
                        try:
                                self.PLCconn.closeConnection()
                                close_status.append("PLC connection closed successfully")
                                print("PLC connection closed")
                        except Exception as e:
                                close_status.append(f"Error closing PLC: {e}")
                                print(f"Error closing PLC: {e}")
                        finally:
                                self.PLCconn = None
                
                # Print status to console
                for status in close_status:
                        print(status)

        def cleanup_on_exit(self):
                print("Program is exiting... cleaning up connections")
                self.cleanup_connections()
#####################        #END OF THE CLASS UI MAINWINDOW #########################################
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
